name: Update Wait Times Data

# This workflow is currently disabled (commented out)
# To enable it, uncomment the schedule section below
on:
  # schedule:
  #   # Runs every 15 minutes starting at 10:01 AM ET
  #   - cron: '1,16,31,46 * * * *'
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pytz
        
    - name: Run data extraction script
      run: |
        python extract_today_data.py
        
    - name: Check if data file was created
      run: |
        ls -la data/today_waits_*.json
        echo "Data file check completed"
        
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/today_waits_*.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update wait times data [skip ci]" && git push)
        
    - name: Show summary
      run: |
        echo "Workflow completed at $(date)"
        echo "Latest data file:"
        ls -la data/today_waits_*.json | tail -1 